# Generated by Django 4.1.6 on 2023-04-20 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Data Visualization'},
        ),
    ]
